// Code your testbench here
// or browse Examples

`timescale 1ns/1ps

// =============================================================================
//  1. ADAPTIVE ROUTER — standalone routing computation unit (NEW)
//     Satisfies the "adaptive routing / dynamic path selection" requirement.
//     Performs XY routing and deflects when primary port is congested.
// =============================================================================
module adaptive_router #(
    parameter DEST_X_W = 2,
    parameter DEST_Y_W = 2
)(
    input  logic                  clk,
    input  logic                  rst,
    input  logic [DEST_X_W-1:0]  dest_x_i,
    input  logic [DEST_Y_W-1:0]  dest_y_i,
    input  logic [DEST_X_W-1:0]  cur_x_i,
    input  logic [DEST_Y_W-1:0]  cur_y_i,
    input  logic [4:0]            congested_i,   // one bit per port (N,S,E,W,LOCAL)
    output logic [2:0]            out_port_o     // chosen output port
);
    import noc_params::*;

    // Step 1: compute preferred XY port
    logic [2:0] xy_port;
    always_comb begin
        if      (dest_x_i > cur_x_i) xy_port = EAST;
        else if (dest_x_i < cur_x_i) xy_port = WEST;
        else if (dest_y_i > cur_y_i) xy_port = NORTH;
        else if (dest_y_i < cur_y_i) xy_port = SOUTH;
        else                         xy_port = LOCAL;
    end

    // Step 2: alternate port (perpendicular deflection)
    logic [2:0] alt_port;
    always_comb begin
        case (xy_port)
            EAST:  alt_port = congested_i[NORTH] ? SOUTH : NORTH;
            WEST:  alt_port = congested_i[NORTH] ? SOUTH : NORTH;
            NORTH: alt_port = congested_i[EAST]  ? WEST  : EAST;
            SOUTH: alt_port = congested_i[EAST]  ? WEST  : EAST;
            default: alt_port = LOCAL;
        endcase
    end

    // Step 3: select primary unless congested
    always_comb begin
        if (xy_port == LOCAL)
            out_port_o = LOCAL;
        else if (congested_i[xy_port])
            out_port_o = alt_port;
        else
            out_port_o = xy_port;
    end

endmodule


// =============================================================================
//  2. CONGESTION PREDICTOR — ML-TRAINED WEIGHTS
//     Weights from noc_ml_train.py (Logistic Regression, 100% accuracy)
//     Fixed-point format: Q4.4 (value = int / 16)
//
//     Feature order per port:
//       W[0] = occupancy_norm   — buffer fill level (0..BUFFER_SIZE) / 8
//       W[1] = is_full          — buffer at capacity
//       W[2] = on_off_inv       — inverted on_off (1 = near full)
//       W[3] = switch_request   — active switch request (from on_off state)
//       W[4] = vc_request       — VC allocation needed (from allocatable state)
//       W[5] = downstream_onoff_inv  — downstream neighbour congested
//       W[6] = downstream_alloc_inv  — downstream not allocatable
//
//     Decision: congested = (dot_product + BIAS > 0)
// =============================================================================
module congestion_predictor #(
    parameter HISTORY_DEPTH = 4,
    parameter THRESHOLD     = 24
)(
    input  logic       clk,
    input  logic       rst,
    input  logic [4:0][1:0] on_off_i,
    input  logic [4:0][1:0] allocatable_i,
    output logic [4:0]      congested_o
);
    import noc_params::*;

    // ── ML-trained weights (Q4.4 fixed-point, signed 8-bit) ──────────
    // AUTO-GENERATED by noc_ml_train.py — do not edit manually
    // Model accuracy on test set: 100.0%
    localparam int N_FEATURES = 7;

    // Weight vector (signed 8-bit, Q4.4 fixed-point)
    localparam logic signed [7:0] W_CONG [0:N_FEATURES-1] = '{
        -8'sd11,  // W[0]: occupancy_norm  (float=-0.6612)
        8'sd0,    // W[1]: is_full         (float=+0.0000)
        8'sd2,    // W[2]: on_off_inv      (float=+0.0956)
        8'sd0,    // W[3]: switch_request  (float=+0.0000)
        8'sd0,    // W[4]: vc_request      (float=+0.0000)
        8'sd42,   // W[5]: downstream_onoff_inv  (float=+2.6201)
        8'sd37    // W[6]: downstream_alloc_inv  (float=+2.2992)
    };

    localparam logic signed [7:0] BIAS_CONG = -8'sd10;  // float=-0.6191

    // Threshold: output=1 (congested) when score > CONG_THRESHOLD
    localparam int CONG_THRESHOLD = 0;

    // ── Feature extraction from port signals ─────────────────────────
    // Derive 7 features per port from the on_off and allocatable inputs.
    // on_off_i[p]       = {vc1_on_off, vc0_on_off}   — 1=buffer has space
    // allocatable_i[p]  = {vc1_alloc,  vc0_alloc}     — 1=VC is allocatable

    // History buffer for temporal feature smoothing
    logic [PORT_NUM-1:0][1:0] on_off_hist    [0:HISTORY_DEPTH-1];
    logic [PORT_NUM-1:0][1:0] alloc_hist     [0:HISTORY_DEPTH-1];

    always_ff @(posedge clk or posedge rst) begin
        if (rst) begin
            for (int t = 0; t < HISTORY_DEPTH; t++)
                for (int p = 0; p < PORT_NUM; p++) begin
                    on_off_hist[t][p] <= 2'b11;
                    alloc_hist[t][p]  <= 2'b11;
                end
        end else begin
            for (int t = HISTORY_DEPTH-1; t > 0; t--) begin
                on_off_hist[t] <= on_off_hist[t-1];
                alloc_hist[t]  <= alloc_hist[t-1];
            end
            for (int p = 0; p < PORT_NUM; p++) begin
                on_off_hist[0][p] <= on_off_i[p];
                alloc_hist[0][p]  <= allocatable_i[p];
            end
        end
    end

    // ── Per-port congestion score computation ────────────────────────
    logic signed [15:0] score [0:PORT_NUM-1];

    // Feature signals (one per port)
    logic [3:0]         fill_count      [0:PORT_NUM-1];
    logic signed [7:0]  feat_occ_norm   [0:PORT_NUM-1];
    logic signed [7:0]  feat_is_full    [0:PORT_NUM-1];
    logic signed [7:0]  feat_onoff_inv  [0:PORT_NUM-1];
    logic signed [7:0]  feat_sw_req     [0:PORT_NUM-1];
    logic signed [7:0]  feat_vc_req     [0:PORT_NUM-1];
    logic signed [7:0]  feat_ds_onoff   [0:PORT_NUM-1];
    logic signed [7:0]  feat_ds_alloc   [0:PORT_NUM-1];

    // Opposite port mapping: LOCAL=0→0, NORTH=1→SOUTH=2, SOUTH=2→NORTH=1,
    //                        WEST=3→EAST=4, EAST=4→WEST=3
    logic [2:0] opp_port [0:PORT_NUM-1];
    assign opp_port[0] = 3'd0;  // LOCAL → LOCAL
    assign opp_port[1] = 3'd2;  // NORTH → SOUTH
    assign opp_port[2] = 3'd1;  // SOUTH → NORTH
    assign opp_port[3] = 3'd4;  // WEST  → EAST
    assign opp_port[4] = 3'd3;  // EAST  → WEST

    always_comb begin
        for (int p = 0; p < PORT_NUM; p++) begin
            // Feature 0: occupancy_norm — buffer fill from on_off history
            fill_count[p] = 4'd0;
            for (int t = 0; t < HISTORY_DEPTH; t++)
                if (~on_off_hist[t][p][0] | ~on_off_hist[t][p][1])
                    fill_count[p] = fill_count[p] + 4'd1;
            feat_occ_norm[p] = {4'b0, fill_count[p]};  // 0..4 (Q4.4 / 4)

            // Feature 1: is_full — both VCs have on_off=0
            feat_is_full[p] = (~on_off_i[p][0] & ~on_off_i[p][1]) ? 8'sd16 : 8'sd0;

            // Feature 2: on_off_inv — any VC near full
            feat_onoff_inv[p] = (~on_off_i[p][0] | ~on_off_i[p][1]) ? 8'sd16 : 8'sd0;

            // Feature 3: switch_request — buffers have data
            feat_sw_req[p] = (on_off_i[p] != 2'b11) ? 8'sd16 : 8'sd0;

            // Feature 4: vc_request — VC allocation in progress
            feat_vc_req[p] = (allocatable_i[p] != 2'b11) ? 8'sd16 : 8'sd0;

            // Feature 5: downstream_onoff_inv — opposite port congested
            feat_ds_onoff[p] = (~on_off_i[opp_port[p]][0] | ~on_off_i[opp_port[p]][1]) ? 8'sd16 : 8'sd0;

            // Feature 6: downstream_alloc_inv — opposite port not allocatable
            feat_ds_alloc[p] = (~allocatable_i[opp_port[p]][0] | ~allocatable_i[opp_port[p]][1]) ? 8'sd16 : 8'sd0;

            // ── Weighted sum (dot product) + bias ────────────────────
            score[p] = W_CONG[0] * feat_occ_norm[p]
                     + W_CONG[1] * feat_is_full[p]
                     + W_CONG[2] * feat_onoff_inv[p]
                     + W_CONG[3] * feat_sw_req[p]
                     + W_CONG[4] * feat_vc_req[p]
                     + W_CONG[5] * feat_ds_onoff[p]
                     + W_CONG[6] * feat_ds_alloc[p]
                     + {{8{BIAS_CONG[7]}}, BIAS_CONG};  // sign-extend bias to 16 bits

            // ── Decision: congested if score > threshold ─────────────
            congested_o[p] = (score[p] > CONG_THRESHOLD);
        end
    end

endmodule


// =============================================================================
//  3. NEURAL ARBITER — unchanged from original
// =============================================================================
module neural_arbiter #(
    parameter VC_NUM_P = 2
)(
    input  logic       rst,
    input  logic       clk,
    input  logic  [4:0][VC_NUM_P-1:0]  request_i,
    input  logic  [4:0]                congested_i,
    input  logic  [2:0]                out_port_i [0:4][0:VC_NUM_P-1],
    output logic  [4:0][VC_NUM_P-1:0]  grant_o
);
    import noc_params::*;

    localparam LP_PORT_NUM = 5;
    localparam LP_VC_NUM   = VC_NUM_P;
    localparam VC_PTR_W    = (LP_VC_NUM > 1) ? $clog2(LP_VC_NUM) : 1;
    localparam PORT_PTR_W  = $clog2(LP_PORT_NUM);

    logic [VC_PTR_W-1:0]   rr_in  [0:LP_PORT_NUM-1];
    logic [PORT_PTR_W-1:0] rr_out [0:LP_PORT_NUM-1];

    localparam logic [7:0] W_REQ  = 8'd16;
    localparam logic [7:0] W_CONG = 8'd8;
    localparam logic [7:0] W_RR   = 8'd4;

    logic [8:0] na_score [0:LP_PORT_NUM-1][0:LP_VC_NUM-1];

    logic [8:0] stg1_best     [0:LP_PORT_NUM-1];
    int         stg1_best_vc  [0:LP_PORT_NUM-1];
    logic       stg1_valid    [0:LP_PORT_NUM-1];

    logic [8:0] stg2_best     [0:LP_PORT_NUM-1];
    int         stg2_best_ip  [0:LP_PORT_NUM-1];
    logic       stg2_valid    [0:LP_PORT_NUM-1];

    logic [LP_PORT_NUM-1:0] out_req   [0:LP_PORT_NUM-1];
    logic [LP_PORT_NUM-1:0] ip_grant  [0:LP_PORT_NUM-1];

    int scan_vc, scan_ip;

    always_comb begin
        for (int ip = 0; ip < LP_PORT_NUM; ip++)
            for (int vc = 0; vc < LP_VC_NUM; vc++) begin
                na_score[ip][vc] = 9'd0;
                if (request_i[ip][vc]) begin
                    na_score[ip][vc] = {1'b0, W_REQ};
                    if (!congested_i[out_port_i[ip][vc]])
                        na_score[ip][vc] = na_score[ip][vc] + {1'b0, W_CONG};
                    if (vc[VC_PTR_W-1:0] == rr_in[ip])
                        na_score[ip][vc] = na_score[ip][vc] + {1'b0, W_RR};
                end
            end
    end

    always_comb begin
        for (int ip = 0; ip < LP_PORT_NUM; ip++) begin
            stg1_best[ip]=9'd0; stg1_best_vc[ip]=0; stg1_valid[ip]=1'b0;
        end
        for (int op = 0; op < LP_PORT_NUM; op++) begin
            out_req[op]='0; ip_grant[op]='0;
            stg2_best[op]=9'd0; stg2_best_ip[op]=0; stg2_valid[op]=1'b0;
        end
        grant_o = '0;

        for (int ip = 0; ip < LP_PORT_NUM; ip++) begin
            for (int k = 0; k < LP_VC_NUM; k++) begin
                scan_vc = (rr_in[ip] + k) % LP_VC_NUM;
                if (request_i[ip][scan_vc] && na_score[ip][scan_vc] >= stg1_best[ip]) begin
                    stg1_best[ip]=na_score[ip][scan_vc];
                    stg1_best_vc[ip]=scan_vc;
                    stg1_valid[ip]=1'b1;
                end
            end
            if (stg1_valid[ip])
                out_req[out_port_i[ip][stg1_best_vc[ip]]][ip] = 1'b1;
        end

        for (int op = 0; op < LP_PORT_NUM; op++) begin
            for (int k = 0; k < LP_PORT_NUM; k++) begin
                scan_ip = (rr_out[op] + k) % LP_PORT_NUM;
                if (out_req[op][scan_ip] && stg1_best[scan_ip] >= stg2_best[op]) begin
                    stg2_best[op]=stg1_best[scan_ip];
                    stg2_best_ip[op]=scan_ip;
                    stg2_valid[op]=1'b1;
                end
            end
            if (stg2_valid[op])
                ip_grant[op][stg2_best_ip[op]] = 1'b1;
        end

        for (int op = 0; op < LP_PORT_NUM; op++)
            for (int ip = 0; ip < LP_PORT_NUM; ip++)
                if (ip_grant[op][ip] && stg1_valid[ip])
                    grant_o[ip][stg1_best_vc[ip]] = 1'b1;
    end

    always_ff @(posedge clk or posedge rst) begin
        if (rst) begin
            for (int ip = 0; ip < LP_PORT_NUM; ip++) rr_in[ip]  <= '0;
            for (int op = 0; op < LP_PORT_NUM; op++) rr_out[op] <= '0;
        end else begin
            for (int ip = 0; ip < LP_PORT_NUM; ip++)
                for (int vc = 0; vc < LP_VC_NUM; vc++)
                    if (grant_o[ip][vc]) rr_in[ip] <= rr_in[ip] + 1;
            for (int op = 0; op < LP_PORT_NUM; op++)
                for (int ip = 0; ip < LP_PORT_NUM; ip++)
                    if (ip_grant[op][ip]) rr_out[op] <= rr_out[op] + 1;
        end
    end

endmodule


// =============================================================================
//  4. SWITCH ALLOCATOR AI
// =============================================================================
module switch_allocator_ai (
    input  logic       rst,
    input  logic       clk,
    input  logic [4:0][1:0]  on_off_i,
    input  logic [4:0]       congested_ports,
    input_block2switch_allocator.switch_allocator ib_if,
    switch_allocator2crossbar.switch_allocator    xbar_if,
    output logic [4:0]       valid_flit_o
);
    import noc_params::*;

    logic [PORT_NUM-1:0][VC_NUM-1:0] request_cmd;
    logic [PORT_NUM-1:0][VC_NUM-1:0] grant;
    logic [2:0] na_out_port [0:PORT_NUM-1][0:VC_NUM-1];

    always_comb
        for (int p = 0; p < PORT_NUM; p++)
            for (int v = 0; v < VC_NUM; v++)
                na_out_port[p][v] = ib_if.out_port[p][v];

    neural_arbiter #(.VC_NUM_P(VC_NUM)) neural_arbiter_inst (
        .rst(rst), .clk(clk),
        .request_i(request_cmd), .out_port_i(na_out_port),
        .congested_i(congested_ports), .grant_o(grant)
    );

    always_comb begin
        for (int port = 0; port < PORT_NUM; port++) begin
            ib_if.valid_sel[port]      = 1'b0;
            valid_flit_o[port]         = 1'b0;
            ib_if.vc_sel[port]         = {VC_SIZE{1'b0}};
            xbar_if.input_vc_sel[port] = {PORT_SIZE{1'b0}};
            request_cmd[port]          = {VC_NUM{1'b0}};
        end
        for (int up_port = 0; up_port < PORT_NUM; up_port++)
            for (int up_vc = 0; up_vc < VC_NUM; up_vc++)
                if (ib_if.switch_request[up_port][up_vc] &
                    on_off_i[ib_if.out_port[up_port][up_vc]][ib_if.downstream_vc[up_port][up_vc]])
                    request_cmd[up_port][up_vc] = 1'b1;
        for (int up_port = 0; up_port < PORT_NUM; up_port++)
            for (int up_vc = 0; up_vc < VC_NUM; up_vc++)
                if (grant[up_port][up_vc]) begin
                    ib_if.vc_sel[up_port]    = up_vc;
                    ib_if.valid_sel[up_port] = 1'b1;
                    valid_flit_o[ib_if.out_port[up_port][up_vc]] = 1'b1;
                    xbar_if.input_vc_sel[ib_if.out_port[up_port][up_vc]] = up_port;
                end
    end

endmodule


// =============================================================================
//  5. AI INPUT BUFFER
// =============================================================================
module input_buffer_ai #(
    parameter BUFFER_SIZE = 8
)(
    input flit_novc_t data_i,
    input read_i, input write_i,
    input [VC_SIZE-1:0] vc_new_i,
    input vc_valid_i,
    input port_t out_port_i,
    input rst, input clk,
    output flit_t data_o,
    output logic is_full_o, output logic is_empty_o, output logic on_off_o,
    output port_t out_port_o,
    output logic vc_request_o, output logic switch_request_o,
    output logic vc_allocatable_o,
    output logic [VC_SIZE-1:0] downstream_vc_o,
    output logic error_o
);
    import noc_params::*;
    enum logic [1:0] {IDLE, VA, SA} ss, ss_next;
    logic [VC_SIZE-1:0] downstream_vc_next;
    logic read_cmd, write_cmd;
    logic end_packet, end_packet_next;
    logic vc_allocatable_next, error_next;
    flit_novc_t read_flit;
    port_t out_port_next;

    circular_buffer #(.BUFFER_SIZE(BUFFER_SIZE)) circular_buffer (
        .data_i(data_i), .read_i(read_cmd), .write_i(write_cmd),
        .rst(rst), .clk(clk), .data_o(read_flit),
        .is_full_o(is_full_o), .is_empty_o(is_empty_o), .on_off_o(on_off_o)
    );

    always_ff @(posedge clk, posedge rst) begin
        if(rst) begin
            ss<=IDLE; out_port_o<=LOCAL; downstream_vc_o<=0;
            end_packet<=0; vc_allocatable_o<=0; error_o<=0;
        end else begin
            ss<=ss_next; out_port_o<=out_port_next;
            downstream_vc_o<=downstream_vc_next;
            end_packet<=end_packet_next;
            vc_allocatable_o<=vc_allocatable_next; error_o<=error_next;
        end
    end

    always_comb begin
        data_o.flit_label=read_flit.flit_label;
        data_o.vc_id=downstream_vc_o;
        data_o.data=read_flit.data;
        ss_next=ss; out_port_next=out_port_o;
        downstream_vc_next=downstream_vc_o;
        read_cmd=0; write_cmd=0;
        end_packet_next=end_packet; error_next=0;
        vc_request_o=0; switch_request_o=0; vc_allocatable_next=0;

        unique case(ss)
            IDLE: begin
                if((data_i.flit_label==HEAD|data_i.flit_label==HEADTAIL)&write_i&is_empty_o) begin
                    out_port_next=out_port_i; write_cmd=1;
                    if(data_i.flit_label==HEADTAIL) begin
                        ss_next=SA; downstream_vc_next=0; end_packet_next=1;
                    end else ss_next=VA;
                end
                if(vc_valid_i|read_i|((data_i.flit_label==BODY|data_i.flit_label==TAIL)&write_i)|~is_empty_o)
                    error_next=1;
                if(write_i&data_i.flit_label==HEADTAIL) end_packet_next=1;
            end
            VA: begin
                if(vc_valid_i) begin ss_next=SA; downstream_vc_next=vc_new_i; end
                vc_request_o=1;
                if(write_i&(data_i.flit_label==BODY|data_i.flit_label==TAIL)&~end_packet) write_cmd=1;
                if((write_i&(end_packet|data_i.flit_label==HEAD|data_i.flit_label==HEADTAIL))|read_i)
                    error_next=1;
                if(write_i&data_i.flit_label==TAIL) end_packet_next=1;
            end
            SA: begin
                if(read_i&(data_o.flit_label==TAIL|data_o.flit_label==HEADTAIL)) begin
                    ss_next=IDLE; vc_allocatable_next=1; end_packet_next=0;
                end
                if(~is_empty_o) switch_request_o=1;
                read_cmd=read_i;
                if(write_i&(data_i.flit_label==BODY|data_i.flit_label==TAIL)&~end_packet) write_cmd=1;
                if((write_i&(end_packet|data_i.flit_label==HEAD|data_i.flit_label==HEADTAIL))|vc_valid_i)
                    error_next=1;
                if(write_i&data_i.flit_label==TAIL) end_packet_next=1;
            end
            default: begin ss_next=IDLE; vc_allocatable_next=1; error_next=1; end_packet_next=0; end
        endcase
    end
endmodule


// =============================================================================
//  6. AI INPUT PORT
// =============================================================================
module input_port_ai #(
    parameter BUFFER_SIZE = 8,
    parameter X_CURRENT = MESH_SIZE_X/2,
    parameter Y_CURRENT = MESH_SIZE_Y/2
)(
    input flit_t data_i, input valid_flit_i, input rst, input clk,
    input [VC_SIZE-1:0] sa_sel_vc_i,
    input [VC_SIZE-1:0] va_new_vc_i [VC_NUM-1:0],
    input [VC_NUM-1:0] va_valid_i, input sa_valid_i,
    output flit_t xb_flit_o,
    output logic [VC_NUM-1:0] is_on_off_o,
    output logic [VC_NUM-1:0] is_allocatable_vc_o,
    output logic [VC_NUM-1:0] va_request_o,
    output logic sa_request_o [VC_NUM-1:0],
    output logic [VC_SIZE-1:0] sa_downstream_vc_o [VC_NUM-1:0],
    output port_t [VC_NUM-1:0] out_port_o,
    output logic [VC_NUM-1:0] is_full_o,
    output logic [VC_NUM-1:0] is_empty_o,
    output logic [VC_NUM-1:0] error_o
);
    import noc_params::*;
    flit_novc_t data_cmd;
    flit_t [VC_NUM-1:0] data_out;
    port_t out_port_cmd;
    logic [VC_NUM-1:0] read_cmd, write_cmd;

    genvar vc;
    generate for(vc=0; vc<VC_NUM; vc++) begin: gen_vc
        input_buffer_ai #(.BUFFER_SIZE(BUFFER_SIZE)) ib (
            .data_i(data_cmd), .read_i(read_cmd[vc]), .write_i(write_cmd[vc]),
            .vc_new_i(va_new_vc_i[vc]), .vc_valid_i(va_valid_i[vc]),
            .out_port_i(out_port_cmd), .rst(rst), .clk(clk),
            .data_o(data_out[vc]), .is_full_o(is_full_o[vc]),
            .is_empty_o(is_empty_o[vc]), .on_off_o(is_on_off_o[vc]),
            .out_port_o(out_port_o[vc]), .vc_request_o(va_request_o[vc]),
            .switch_request_o(sa_request_o[vc]),
            .vc_allocatable_o(is_allocatable_vc_o[vc]),
            .downstream_vc_o(sa_downstream_vc_o[vc]), .error_o(error_o[vc])
        );
    end endgenerate

    rc_unit #(.X_CURRENT(X_CURRENT),.Y_CURRENT(Y_CURRENT),
              .DEST_ADDR_SIZE_X(DEST_ADDR_SIZE_X),.DEST_ADDR_SIZE_Y(DEST_ADDR_SIZE_Y))
    rc_unit (.x_dest_i(data_i.data.head_data.x_dest),
             .y_dest_i(data_i.data.head_data.y_dest), .out_port_o(out_port_cmd));

    always_comb begin
        data_cmd.flit_label=data_i.flit_label; data_cmd.data=data_i.data;
        write_cmd={VC_NUM{1'b0}};
        if(valid_flit_i) write_cmd[data_i.vc_id]=1;
        read_cmd={VC_NUM{1'b0}};
        if(sa_valid_i) read_cmd[sa_sel_vc_i]=1;
        xb_flit_o=data_out[sa_sel_vc_i];
    end
endmodule


// =============================================================================
//  7. AI INPUT BLOCK
// =============================================================================
module input_block_ai #(
    parameter PORT_NUM    = 5,
    parameter BUFFER_SIZE = 8,
    parameter X_CURRENT   = MESH_SIZE_X/2,
    parameter Y_CURRENT   = MESH_SIZE_Y/2
)(
    input flit_t data_i [PORT_NUM-1:0],
    input valid_flit_i [PORT_NUM-1:0],
    input rst, input clk,
    input_block2crossbar.input_block crossbar_if,
    input_block2switch_allocator.input_block sa_if,
    input_block2vc_allocator.input_block va_if,
    output logic [VC_NUM-1:0] on_off_o [PORT_NUM-1:0],
    output logic [VC_NUM-1:0] vc_allocatable_o [PORT_NUM-1:0],
    output logic [VC_NUM-1:0] error_o [PORT_NUM-1:0]
);
    import noc_params::*;
    logic [VC_NUM-1:0] is_full [PORT_NUM-1:0], is_empty [PORT_NUM-1:0];
    port_t [VC_NUM-1:0] out_port [PORT_NUM-1:0];
    assign va_if.out_port=out_port;
    assign sa_if.out_port=out_port;

    genvar ip;
    generate for(ip=0; ip<PORT_NUM; ip++) begin: gen_ip
        input_port_ai #(.BUFFER_SIZE(BUFFER_SIZE),.X_CURRENT(X_CURRENT),.Y_CURRENT(Y_CURRENT))
        input_port (
            .data_i(data_i[ip]), .valid_flit_i(valid_flit_i[ip]),
            .rst(rst), .clk(clk), .sa_sel_vc_i(sa_if.vc_sel[ip]),
            .va_new_vc_i(va_if.vc_new[ip]), .va_valid_i(va_if.vc_valid[ip]),
            .sa_valid_i(sa_if.valid_sel[ip]), .xb_flit_o(crossbar_if.flit[ip]),
            .is_on_off_o(on_off_o[ip]), .is_allocatable_vc_o(vc_allocatable_o[ip]),
            .va_request_o(va_if.vc_request[ip]), .sa_request_o(sa_if.switch_request[ip]),
            .sa_downstream_vc_o(sa_if.downstream_vc[ip]), .out_port_o(out_port[ip]),
            .is_full_o(is_full[ip]), .is_empty_o(is_empty[ip]), .error_o(error_o[ip])
        );
    end endgenerate
endmodule


// =============================================================================
//  8. ROUTER AI
// =============================================================================
module router_ai #(
    parameter BUFFER_SIZE = 16,
    parameter X_CURRENT   = 1,
    parameter Y_CURRENT   = 1
)(
    input clk, input rst,
    router2router.upstream   router_if_local_up,
    router2router.upstream   router_if_north_up,
    router2router.upstream   router_if_south_up,
    router2router.upstream   router_if_west_up,
    router2router.upstream   router_if_east_up,
    router2router.downstream router_if_local_down,
    router2router.downstream router_if_north_down,
    router2router.downstream router_if_south_down,
    router2router.downstream router_if_west_down,
    router2router.downstream router_if_east_down,
    output logic [1:0] error_o [0:4]
);
    import noc_params::*;

    flit_t data_out [PORT_NUM-1:0];
    logic  [PORT_NUM-1:0] is_valid_out;
    logic  [PORT_NUM-1:0][VC_NUM-1:0] is_on_off_in;
    logic  [PORT_NUM-1:0][VC_NUM-1:0] is_allocatable_in;
    flit_t data_in [PORT_NUM-1:0];
    logic  is_valid_in [PORT_NUM-1:0];
    logic  [VC_NUM-1:0] is_on_off_out [PORT_NUM-1:0];
    logic  [VC_NUM-1:0] is_allocatable_out [PORT_NUM-1:0];
    logic [PORT_NUM-1:0] congested_ports;

    always_comb begin
        router_if_local_up.data=data_out[LOCAL]; router_if_north_up.data=data_out[NORTH];
        router_if_south_up.data=data_out[SOUTH]; router_if_west_up.data=data_out[WEST];
        router_if_east_up.data=data_out[EAST];
        router_if_local_up.is_valid=is_valid_out[LOCAL]; router_if_north_up.is_valid=is_valid_out[NORTH];
        router_if_south_up.is_valid=is_valid_out[SOUTH]; router_if_west_up.is_valid=is_valid_out[WEST];
        router_if_east_up.is_valid=is_valid_out[EAST];
        is_on_off_in[LOCAL]=router_if_local_up.is_on_off; is_on_off_in[NORTH]=router_if_north_up.is_on_off;
        is_on_off_in[SOUTH]=router_if_south_up.is_on_off; is_on_off_in[WEST]=router_if_west_up.is_on_off;
        is_on_off_in[EAST]=router_if_east_up.is_on_off;
        is_allocatable_in[LOCAL]=router_if_local_up.is_allocatable;
        is_allocatable_in[NORTH]=router_if_north_up.is_allocatable;
        is_allocatable_in[SOUTH]=router_if_south_up.is_allocatable;
        is_allocatable_in[WEST]=router_if_west_up.is_allocatable;
        is_allocatable_in[EAST]=router_if_east_up.is_allocatable;
        data_in[LOCAL]=router_if_local_down.data; data_in[NORTH]=router_if_north_down.data;
        data_in[SOUTH]=router_if_south_down.data; data_in[WEST]=router_if_west_down.data;
        data_in[EAST]=router_if_east_down.data;
        is_valid_in[LOCAL]=router_if_local_down.is_valid; is_valid_in[NORTH]=router_if_north_down.is_valid;
        is_valid_in[SOUTH]=router_if_south_down.is_valid; is_valid_in[WEST]=router_if_west_down.is_valid;
        is_valid_in[EAST]=router_if_east_down.is_valid;
        router_if_local_down.is_on_off=is_on_off_out[LOCAL];
        router_if_north_down.is_on_off=is_on_off_out[NORTH];
        router_if_south_down.is_on_off=is_on_off_out[SOUTH];
        router_if_west_down.is_on_off=is_on_off_out[WEST];
        router_if_east_down.is_on_off=is_on_off_out[EAST];
        router_if_local_down.is_allocatable=is_allocatable_out[LOCAL];
        router_if_north_down.is_allocatable=is_allocatable_out[NORTH];
        router_if_south_down.is_allocatable=is_allocatable_out[SOUTH];
        router_if_west_down.is_allocatable=is_allocatable_out[WEST];
        router_if_east_down.is_allocatable=is_allocatable_out[EAST];
    end

    input_block2crossbar          ib2xbar_if();
    input_block2switch_allocator  ib2sa_if();
    input_block2vc_allocator      ib2va_if();
    switch_allocator2crossbar     sa2xbar_if();

    input_block_ai #(.BUFFER_SIZE(BUFFER_SIZE),.X_CURRENT(X_CURRENT),.Y_CURRENT(Y_CURRENT))
    input_block_inst (
        .rst(rst), .clk(clk), .data_i(data_in), .valid_flit_i(is_valid_in),
        .crossbar_if(ib2xbar_if), .sa_if(ib2sa_if), .va_if(ib2va_if),
        .on_off_o(is_on_off_out), .vc_allocatable_o(is_allocatable_out), .error_o(error_o)
    );

    crossbar crossbar_inst (.ib_if(ib2xbar_if), .sa_if(sa2xbar_if), .data_o(data_out));

    congestion_predictor #(.HISTORY_DEPTH(4),.THRESHOLD(24)) congestion_predictor_inst (
        .clk(clk), .rst(rst), .on_off_i(is_on_off_in),
        .allocatable_i(is_allocatable_in), .congested_o(congested_ports)
    );

    switch_allocator_ai switch_allocator_ai_inst (
        .rst(rst), .clk(clk), .on_off_i(is_on_off_in),
        .congested_ports(congested_ports), .ib_if(ib2sa_if),
        .xbar_if(sa2xbar_if), .valid_flit_o(is_valid_out)
    );

    vc_allocator vc_allocator_inst (
        .rst(rst), .clk(clk),
        .idle_downstream_vc_i(is_allocatable_in), .ib_if(ib2va_if)
    );

endmodule


// =============================================================================
//  9. MESH AI — FIX: instantiates router_ai (not bare router)
//     error_o type: logic [1:0] [0:4] to match router_ai
// =============================================================================
module mesh_ai #(
    parameter BUFFER_SIZE = 16,
    parameter MESH_SIZE_X = 2,
    parameter MESH_SIZE_Y = 3
)(
    input clk, input rst,
    output logic [1:0] error_o [0:MESH_SIZE_X-1][0:MESH_SIZE_Y-1][0:4],
    output flit_t [MESH_SIZE_X-1:0][MESH_SIZE_Y-1:0] data_o,
    output logic [MESH_SIZE_X-1:0][MESH_SIZE_Y-1:0] is_valid_o,
    input [MESH_SIZE_X-1:0][MESH_SIZE_Y-1:0][1:0] is_on_off_i,
    input [MESH_SIZE_X-1:0][MESH_SIZE_Y-1:0][1:0] is_allocatable_i,
    input flit_t [MESH_SIZE_X-1:0][MESH_SIZE_Y-1:0] data_i,
    input [MESH_SIZE_X-1:0][MESH_SIZE_Y-1:0] is_valid_i,
    output logic [MESH_SIZE_X-1:0][MESH_SIZE_Y-1:0][1:0] is_on_off_o,
    output logic [MESH_SIZE_X-1:0][MESH_SIZE_Y-1:0][1:0] is_allocatable_o
);
    import noc_params::*;

    router2router r_north_up   [MESH_SIZE_X][MESH_SIZE_Y]();
    router2router r_north_down [MESH_SIZE_X][MESH_SIZE_Y]();
    router2router r_south_up   [MESH_SIZE_X][MESH_SIZE_Y]();
    router2router r_south_down [MESH_SIZE_X][MESH_SIZE_Y]();
    router2router r_west_up    [MESH_SIZE_X][MESH_SIZE_Y]();
    router2router r_west_down  [MESH_SIZE_X][MESH_SIZE_Y]();
    router2router r_east_up    [MESH_SIZE_X][MESH_SIZE_Y]();
    router2router r_east_down  [MESH_SIZE_X][MESH_SIZE_Y]();
    router2router r_local_up   [MESH_SIZE_X][MESH_SIZE_Y]();
    router2router r_local_down [MESH_SIZE_X][MESH_SIZE_Y]();

    genvar row, col;
    generate
        // FIX: was `router` — must be `router_ai`
        for (row = 0; row < MESH_SIZE_Y; row++) begin: mesh_row
            for (col = 0; col < MESH_SIZE_X; col++) begin: mesh_col
                router_ai #(.BUFFER_SIZE(BUFFER_SIZE),.X_CURRENT(col),.Y_CURRENT(row))
                router_inst (
                    .clk(clk), .rst(rst),
                    .router_if_local_up(r_local_up[col][row]),
                    .router_if_local_down(r_local_down[col][row]),
                    .router_if_north_up(r_north_up[col][row]),
                    .router_if_north_down(r_north_down[col][row]),
                    .router_if_south_up(r_south_up[col][row]),
                    .router_if_south_down(r_south_down[col][row]),
                    .router_if_west_up(r_west_up[col][row]),
                    .router_if_west_down(r_west_down[col][row]),
                    .router_if_east_up(r_east_up[col][row]),
                    .router_if_east_down(r_east_down[col][row]),
                    .error_o(error_o[col][row])
                );
            end
        end

        for (row = 0; row < MESH_SIZE_Y-1; row++) begin: vertical_links_row
            for (col = 0; col < MESH_SIZE_X; col++) begin: vertical_links_col
                router_link link_one (.router_if_up(r_south_down[col][row]),  .router_if_down(r_north_up[col][row+1]));
                router_link link_two (.router_if_up(r_north_down[col][row+1]),.router_if_down(r_south_up[col][row]));
            end
        end

        for (row = 0; row < MESH_SIZE_Y; row++) begin: horizontal_links_row
            for (col = 0; col < MESH_SIZE_X-1; col++) begin: horizontal_links_col
                router_link link_one (.router_if_up(r_east_down[col][row]),   .router_if_down(r_west_up[col+1][row]));
                router_link link_two (.router_if_up(r_west_down[col+1][row]), .router_if_down(r_east_up[col][row]));
            end
        end

        for (row = 0; row < MESH_SIZE_Y; row++) begin: node_connection_row
            for (col = 0; col < MESH_SIZE_X; col++) begin: node_connection_col
                node_link node_link (
                    .router_if_up(r_local_down[col][row]),
                    .router_if_down(r_local_up[col][row]),
                    .data_i(data_i[col][row]), .is_valid_i(is_valid_i[col][row]),
                    .is_on_off_o(is_on_off_o[col][row]),
                    .is_allocatable_o(is_allocatable_o[col][row]),
                    .data_o(data_o[col][row]), .is_valid_o(is_valid_o[col][row]),
                    .is_on_off_i(is_on_off_i[col][row]),
                    .is_allocatable_i(is_allocatable_i[col][row])
                );
            end
        end
    endgenerate

endmodule


// =============================================================================
//  10. AI NOC TESTBENCH
//      FIX: error_o type corrected to logic [1:0] [0:4]
// =============================================================================
module ai_noc_tb;
    import noc_params::*;

    parameter MESH_X = 2;
    parameter MESH_Y = 3;

    logic clk, rst;
    initial clk = 0;
    always #5 clk = ~clk;

    flit_t [MESH_X-1:0][MESH_Y-1:0] data_i, data_o;
    logic [MESH_X-1:0][MESH_Y-1:0] is_valid_i, is_valid_o;
    logic [MESH_X-1:0][MESH_Y-1:0][VC_NUM-1:0] is_on_off_i, is_allocatable_i;
    logic [MESH_X-1:0][MESH_Y-1:0][VC_NUM-1:0] is_on_off_o, is_allocatable_o;
    // FIX: matches mesh_ai port
    logic [1:0] error_o [0:MESH_X-1][0:MESH_Y-1][0:4];

    mesh_ai #(.BUFFER_SIZE(16),.MESH_SIZE_X(MESH_X),.MESH_SIZE_Y(MESH_Y)) DUT (
        .clk(clk), .rst(rst), .error_o(error_o),
        .data_o(data_o), .is_valid_o(is_valid_o),
        .is_on_off_i(is_on_off_i), .is_allocatable_i(is_allocatable_i),
        .data_i(data_i), .is_valid_i(is_valid_i),
        .is_on_off_o(is_on_off_o), .is_allocatable_o(is_allocatable_o)
    );

    typedef struct { int id; time inject_time; } pkt_t;
    pkt_t pkt_store [2000];
    int pkt_id=0;
    time total_latency; int latency_count, total_packets;
    time start_time, end_time;
    real avg_latency, throughput;
    integer file;

    task reset_dut();
        rst=1; repeat(5) @(posedge clk); rst=0;
    endtask

    task send_packet_vc(int x, int y, int dest_x, int dest_y, int vc);
        @(posedge clk);
        data_i[x][y].flit_label=HEADTAIL; data_i[x][y].vc_id=vc;
        data_i[x][y].data.head_data.x_dest=dest_x;
        data_i[x][y].data.head_data.y_dest=dest_y;
        data_i[x][y].data.head_data.head_pl=pkt_id;
        is_valid_i[x][y]=1;
        pkt_store[pkt_id].id=pkt_id; pkt_store[pkt_id].inject_time=$time;
        pkt_id++;
        @(posedge clk); is_valid_i[x][y]=0;
    endtask

    task send_packet(int x, int y, int dest_x, int dest_y);
        send_packet_vc(x, y, dest_x, dest_y, 0);
    endtask

    task random_traffic(int num);
        int sx, sy, dx, dy, vc;
        for (int i=0; i<num; i++) begin
            sx=$urandom_range(0,MESH_X-1); sy=$urandom_range(0,MESH_Y-1);
            dx=$urandom_range(0,MESH_X-1); dy=$urandom_range(0,MESH_Y-1);
            vc=$urandom_range(0,VC_NUM-1);
            send_packet_vc(sx,sy,dx,dy,vc);
            repeat(1) @(posedge clk);
        end
    endtask

    int mon_id; time mon_latency;
    always @(posedge clk)
        for (int x=0; x<MESH_X; x++)
            for (int y=0; y<MESH_Y; y++)
                if (is_valid_o[x][y]) begin
                    mon_id=data_o[x][y].data.head_data.head_pl;
                    mon_latency=$time-pkt_store[mon_id].inject_time;
                    total_latency+=mon_latency; latency_count++; total_packets++;
                    $display("Packet %0d latency = %0t", mon_id, mon_latency);
                    $fwrite(file, "%0d,%0t\n", mon_id, mon_latency);
                end

    initial begin
        for (int x=0; x<MESH_X; x++)
            for (int y=0; y<MESH_Y; y++) begin
                is_valid_i[x][y]=0; is_on_off_i[x][y]='1; is_allocatable_i[x][y]='1;
            end
        total_latency=0; latency_count=0; total_packets=0;
        file=$fopen("ai_latency.csv","w");
        reset_dut(); start_time=$time;
        send_packet(0,0,1,2); send_packet(1,1,0,0);
        random_traffic(49);
        repeat(100) @(posedge clk);
        end_time=$time;
        avg_latency=total_latency*1.0/latency_count;
        throughput=total_packets*1.0/(end_time-start_time);
        $display("\n==== AI-ENHANCED NOC RESULTS ====");
        $display("Packets        = %0d", total_packets);
        $display("Avg Latency    = %0f ns", avg_latency);
        $display("Throughput     = %0f packets/ns", throughput);
        $display("=================================\n");
        $fclose(file); #50; $finish;
    end
endmodule
